"""create user and agent tables

Revision ID: 75b8d5516fd0
Revises: 
Create Date: 2026-05-09 17:48:47.940734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b8d5516fd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agent_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('launch_metrics_specialist_agent_output', sa.String(), nullable=True),
    sa.Column('market_sentiment_specialist_agent_output', sa.String(), nullable=True),
    sa.Column('product_launch_analyst_agent_output', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_agent_outputs_email'), 'user_agent_outputs', ['email'], unique=True)
    op.create_index(op.f('ix_user_agent_outputs_id'), 'user_agent_outputs', ['id'], unique=False)
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_data_email'), 'user_data', ['email'], unique=True)
    op.create_index(op.f('ix_user_data_id'), 'user_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_data_id'), table_name='user_data')
    op.drop_index(op.f('ix_user_data_email'), table_name='user_data')
    op.drop_table('user_data')
    op.drop_index(op.f('ix_user_agent_outputs_id'), table_name='user_agent_outputs')
    op.drop_index(op.f('ix_user_agent_outputs_email'), table_name='user_agent_outputs')
    op.drop_table('user_agent_outputs')
    # ### end Alembic commands ###
