from pydantic import BaseModel, Field, EmailStr, ConfigDict


class UserCreate(BaseModel):
    """Schema for creating a new user (input payload).

    Used in POST/PUT requests to create or update users. Includes the
    plain-text password which should be hashed before storage.

    Attributes:
        name (str): User display name.
        email (EmailStr): User email address.
        password (str): Plain-text password (will be hashed before storage).
    """

    name: str = Field(..., description="The user's display name")
    email: EmailStr = Field(..., description="The user's email address")
    password: str = Field(..., description="The user's password")


class GetUser(BaseModel):
    """Schema for creating a new user (input payload).

    Used in POST/PUT requests to create or update users. Includes the
    plain-text password which should be hashed before storage.

    Attributes:
        name (str): User display name.
        email (EmailStr): User email address.
        password (str): Plain-text password (will be hashed before storage).
    """

    email: EmailStr = Field(..., description="The user's email address")
    password: str = Field(..., description="The user's password")


class GetUserResponse(BaseModel):
    """Schema for creating a new user (input payload).

    Used in POST/PUT requests to create or update users. Includes the
    plain-text password which should be hashed before storage.

    Attributes:
        name (str): User display name.
        email (EmailStr): User email address.
        password (str): Plain-text password (will be hashed before storage).
    """

    name: str = Field(..., description="The user's display name")
    email: EmailStr = Field(..., description="The user's email address")
    message: str = Field(default="", description="A message confirming user retrieval")


class UserResponse(BaseModel):
    """Schema for user API responses (output payload).

    Returned by GET/POST/PUT endpoints. Excludes the password field for
    security—never expose password hashes in API responses.

    Attributes:
        id (int): Unique user identifier.
        name (str): User display name.
        email (EmailStr): User email address.
    """

    model_config = ConfigDict(from_attributes=True)

    id: int = Field(..., description="The unique identifier of the user")
    name: str = Field(..., description="The user's display name")
    email: EmailStr = Field(..., description="The user's email address")


class AddUserResponse(BaseModel):
    """Schema for user API responses (output payload).

    Returned by GET/POST/PUT endpoints. Excludes the password field for
    security—never expose password hashes in API responses.

    Attributes:
        id (int): Unique user identifier.
        name (str): User display name.
        email (EmailStr): User email address.
    """

    model_config = ConfigDict(from_attributes=True)

    id: int = Field(..., description="The unique identifier of the user")
    name: str = Field(..., description="The user's display name")
    email: EmailStr = Field(..., description="The user's email address")
    message: str = Field(default="", description="A message confirming user creation")


class UserCreateAgentThread(BaseModel):
    """Schema for user agent outputs.

    This schema defines the expected structure of the outputs generated by
    user agents. It can be used to standardize the format of responses from
    agents that process user-related data or perform actions on behalf of
    users.

    Attributes:
        user_id (int): The unique identifier of the user associated with the agent output.
        output (str): The output generated by the user agent, which could be a message, a result of an action, or any relevant information produced by the agent.

    """

    email: EmailStr = Field(
        ...,
        description="The email address of the user associated with the agent output",
    )



class UserAgentThreadResponse(BaseModel):
    """Schema for user agent outputs.

    This schema defines the expected structure of the outputs generated by
    user agents. It can be used to standardize the format of responses from
    agents that process user-related data or perform actions on behalf of
    users.

    Attributes:
        user_id (int): The unique identifier of the user associated with the agent output.
        output (str): The output generated by the user agent, which could be a message, a result of an action, or any relevant information produced by the agent.

    """

    thread_id: str = Field(
        ..., description="The unique identifier for the agent run thread"
    )

    message: str = Field(
        default="User agent thread recorded successfully",
        description="A message confirming that the user agent thread was recorded",
    )
